name: Discord Webhook 連投

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  spam:
    runs-on: ubuntu-latest
    steps:
      - name: Send messages
        run: |
          WEBHOOK_URL="${{ secrets.DISCORD_WEBHOOK_URL }}"
          for i in {1..20}; do
            curl -H "Content-Type: application/json" \
                 -d '{"content": "# # おつかれーろおつからー ('"$i"'/10)"}' \
                 $WEBHOOK_URL
            sleep 0.7
          done
